export default {
  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE',

  TOGGLE_MOBILE_MENU: 'TOGGLE_MOBILE_MENU',
  TOGGLE_AUTHENTICATION_FORM: 'TOGGLE_AUTHENTICATION_FORM',

  LOGIN_FORM_FIELD_CHANGE: 'LOGIN_FORM_FIELD_CHANGE',
  REGISTER_FORM_FIELD_CHANGE: 'REGISTER_FORM_FIELD_CHANGE',
}