export default {

  TOGGLE_MOBILE_MENU: 'TOGGLE_MOBILE_MENU',
  TOGGLE_AUTHENTICATION_FORM: 'TOGGLE_AUTHENTICATION_FORM',
  CHANGE_ON_AUTH_REDIRECT: 'CHANGE_ON_AUTH_REDIRECT',

  LOGIN_FORM_FIELD_CHANGE: 'LOGIN_FORM_FIELD_CHANGE',
  REGISTER_FORM_FIELD_CHANGE: 'REGISTER_FORM_FIELD_CHANGE',

  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE',

  REGISTER_REQUEST: 'REGISTER_REQUEST',
  REGISTER_SUCCESS: 'REGISTER_SUCCESS',
  REGISTER_FAILURE: 'REGISTER_FAILURE',
}