export default {
  TOGGLE_MOBILE_MENU: 'TOGGLE_MOBILE_MENU',
  TOGGLE_AUTHENTICATION_FORM: 'TOGGLE_AUTHENTICATION_FORM',
  CHANGE_ON_AUTH_REDIRECT: 'CHANGE_ON_AUTH_REDIRECT',

  FORM_FIELD_CHANGE: 'FORM_FIELD_CHANGE',
  
  AD_CREATE_REQUEST: 'AD_CREATE_REQUEST',
  AD_CREATE_SUCCESS: 'AD_CREATE_SUCCESS',
  AD_CREATE_FAILURE: 'AD_CREATE_FAILURE',

  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE',

  REGISTER_REQUEST: 'REGISTER_REQUEST',
  REGISTER_SUCCESS: 'REGISTER_SUCCESS',
  REGISTER_FAILURE: 'REGISTER_FAILURE',

  DISMISS_MESSAGE: 'DISMISS_MESSAGE',

  LOGOUT: 'LOGOUT'
}